openapi: 3.0.0

paths:
  /sample:
    get:
      summary: Get a Sample
      responses:
        '200': 
          description: A JSON of samples
          content:
            application/json:
              schema: 
                type: object
                properties:
                  item1:  
                    type: string
                  item2:  
                    type: string